print("|==================================================|")
print("|                DAFTAR FAKULTAS                   |")
print("|==================================================|")
print("|01. Fakultas Hukum dan Bisnis Digital             |")
print("|02. Fakultas Teknologi dan Rekayasa Cerdas        |")
print("|03. Fakultas Humaniora dan Industri Kreatif       |")
print("|04. Fakultas Psikologi                            |")
print("|05. Fakultas Kedokteran Gigi                      |")
print("|06. Fakultas Kedokteran                           |")
print("|==================================================|")